version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend/
    ports:
      - '5000:80'
    links:
      - mongodb
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    ports:
      - '80:80'
    links:
      - backend
